# Generated by Django 5.0.1 on 2024-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_author_rename_user_response_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(default='None', max_length=8),
        ),
    ]
