# Generated by Django 5.0.1 on 2024-01-15 22:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_response_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='content',
            field=tinymce.models.HTMLField(default='Ваш контент'),
        ),
    ]
