# Generated by Django 5.0.1 on 2024-01-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(default='Ваш контент'),
        ),
    ]
